### ISSUE TITLE
Not possible to use RAM for temp file on Hassio

### ISSUE THREAD

**Issue by oyta** [custom-components/sensor.mitemp_bt#25]
**Situation**: I want the tempfile to be written to RAM instead of the SD card. A solution is written in the README, but as far as I understand that doesn't work if using RPi with HASSIO.

**Question**: Is it possible to use the https://pypi.org/project/memory-tempfile/ library and default write to memory instead of the SD card?

**Comment by Magalex2x14** [comment]
We had to roll back to usual tempfile because a bug was found in the lib (spooled temporary file). I was looking for alternatives but apparently looking bad) Thanks for the suggestion! 

There are plans not to use external utilities (that is, there will be no need for a temporary file), but it will not be so soon, so your option looks like a reliable solution.

I will make a beta as soon as possible (this weekend maybe), and we will try this solution.

**Comment by Magalex2x14** [comment]
@oyta please try 0.4.2-beta. Now the component checks the available folders and prefers those located in the RAM. With debugging enabled, logs available and currently used folders.

**Comment by Magalex2x14** [comment]
I found that in the case of HASSio (HassOS), the library you proposed still rolls back to /tmp, because it does not find accessible memory based file systems...

**Comment by Alexious-sh** [comment]
Why don't you use PIPE instead of a temporary file to capture stdout?

**Comment by Magalex2x14** [comment]
@Alexious-sh PIPE has been used since the beginning. But after some study it turned out that the buffer is not enough to accommodate the entire amount of data (hcidump produces a huge amount even with a period of one minute and a small number of devices in the reception area). I spent some time searching for a solution (use a multi-threading with freeing up the buffer as necessary during the measurement period), but since we must switch to another method of data collection (refusing to use an external utility in favor of the python way, preferably Bluez D-Bus #9), then this issue will be solved automatically.

**Comment by Magalex2x14** [comment]
The problem will be solved with  [0.5.0](https://github.com/custom-components/sensor.mitemp_bt/releases/tag/0.5.0-alfa) release. Closing.
