### ISSUE TITLE
Poor performance after moving hassio to ssd

### ISSUE THREAD

**Issue by DendelX** [custom-components/sensor.mitemp_bt#30]
I know it may sound strange, and I don't see a direct relationship, but after moving my hassio installation from sd to an ssd, I have noticed a great loss of performance. I receive much less data from my sensors. Is this something known?

Before change, I had around 30 readings each 2 minutes, but now, some of sensors don't update and others get 1 packet each hour.

**Comment by Magalex2x14** [comment]
No ... It's really weird. What is your hardware? How is SSD connected? What version of the custom.mitemp_bt are you using?

**Comment by DendelX** [comment]
Rpi 3b, hassio last versión, mitemp_bt 0.4.3 (same performance with 0.4.2). I migrate from sd to ssd with a hassio fresh install and a complete snapshot restore. SSD is connected with an adapter to USB. SSD is powered with a power supply. 

I cant see that each sensor has different behavior for temperature and humidity, some has a good temperature data amount and bad humidity. All was great before this migration. 
I've reinstalled mitemp_bt custom but same result.

**Comment by DendelX** [comment]
These images correspond to same sensor, temperature is working great, but humidity only get a few readings. Other sensors has same behaviour and others have little data on both temperature and humidity.

![image](https://user-images.githubusercontent.com/51743530/73257249-ae7bd280-41c3-11ea-87bc-2ecf1901237c.png)
![image](https://user-images.githubusercontent.com/51743530/73257327-db2fea00-41c3-11ea-9caf-625a5dcee48c.png)

**Comment by Magalex2x14** [comment]
I think that the component has nothing to do with it. The only thing is that for the purity of the experiment you can try the latest beta of the 0.5 branch (0.5.3-beta at the moment) - it does not use external utilities and files. To install beta, you need to enable "show betas" option in HACS (three dots menu on the component page).

But I think that installing an SSD has led to a deterioration in reception conditions. You blocked the antenna somehow, or the SSD worsened the electromagnetic environment, that is, it either became a source of interference, or its power source. The probability of this is high, since the RSSI in the second chart is sufficient for normal reception. I have a sensor from which at -95dbm I receive up to 10 measurements:
![image](https://user-images.githubusercontent.com/4982025/73258593-17b91100-41d7-11ea-8030-339371070fb4.png)

Using RSSI, one cannot clearly judge the quality of reception. Another important characteristic is the signal-to-noise ratio (SNR), for example. But we do not have access to it... For example, with a sufficiently high RSSI, we can have a high noise level, and as a result, low reception quality, which is similar to your situation, as it seems to me...

I myself did not study this issue, but I read a lot that BT in RPi, let’s say, could be implemented better... Many people solve the problems connected with this by installing an external USB dongle (there are even options with a full-sized external antenna).

**Comment by DendelX** [comment]
I will try to place the ssd further from the raspberry, I thought the same but I noticed this problem out of home. If I try bete, I could go back later?

**Comment by Magalex2x14** [comment]
Yes, there are no problems with rollback to 0.4. The only thing is that before starting 0.5, you need to check the component settings - the options have changed a bit (reflected in README.md).

**Comment by DendelX** [comment]
ok perfect, thanks a lot @Magalex2x14

**Comment by DendelX** [comment]
I'm not try to place ssd further yet but... I see something a that could be a little suspicious? See:

![image](https://user-images.githubusercontent.com/51743530/73283909-121df400-41f4-11ea-8707-ed2a294afe16.png)

There are 2 diferents sensors in different rooms, but last_packet id are the same, rssi are the same, battery level are the same, last mean are the same... When I use your custom for first time, I renamed sensors from standard name with the mac to my own name. Later, when I migrate to ssd, i need to erase database (mariadb must be uninstalled when restore from snapshot). 

Could be possible a mix of sensors or something like this? How I can start again from empty data? and leave sensors add like first time?

**Comment by Magalex2x14** [comment]
I suggest you to try disable custom.mitemp_bt (comment out in configuration.yaml and restart HA), then go to Configuration -> Entities, delete entities, restart HA, enable custom.mitemp_bt back.

Please, tell us, if this helps.

The component updates entities bound to the device 's mac address. Always. He doesn 't know anything about the renaming, so there 's probably been confusion somewhere else, yes.

**Comment by DendelX** [comment]
I want to share that the problem was the proximity of the SSD to the raspberry. Luckily I was using a sata to usb adapter with cable, not one of those boards with which you put the ssd next to the rasperry. We can learn from everything.

On the other hand, the data mix between the two sensors was present. But I deleted the entities and by activating the custom.mitemp_bt again as you told me it was fixed. Thank you very much, everything is working like a charm right now

**Comment by Ernst79** [comment]
@DendelX I had the same issue in the past, hardly any measurements after moving to an SSD. Moving the SSD away from the raspberry fixed the issue.

**Comment by DendelX** [comment]
Thanks for the feedback @Ernst79, yes, it's incredible that an ssd close to the raspberry makes a big difference in bluetooth range.

**Comment by Magalex2x14** [comment]
Thanks for the feedback. I begin to affirm that I should probably think about collecting the FAQ ... I close it for now. Feel free to reopen, if needed.

**Comment by Ernst79** [comment]
@Magalex2x14 I will make a start with the faq in a separate branch.

**Comment by Magalex2x14** [comment]
OK. Thank you!
